### ISSUE TITLE
Broken in 1.0 (b309)

### ISSUE THREAD

**Issue by ZethRyder** [OCB7D2D/OcbLightEnablerPOI#1]
Just tested to see if it still worked and the moment looking at any light, the dev terminal appears with red text error and freezes the player in place as the error continues to repeat:

**MissingMethodException: Method not found: string . Localization.Get(String)**

I figure with the big update it was going to be broken but figured I should report it regardless. Hoping to see an update to this amazing mod!

**Comment by mgreter** [comment]
TBH no need to report this for any mod, as all mods are expected to not work with new major versions! It will be updated at some point, but having to deal with these reports doesn't help to get time into actual development ... will keep it open though, so other don't open more of these. Thx.

**Comment by vbnet3d** [comment]
FYI @mgreter they made a bunch of private methods public, so your MethodInfo handle is probably null. I had the same issue on my mod

**Comment by mgreter** [comment]
It actually just needs to be compiled against the proper new references.
Release will happen soon, but I want to test each mod I release first.
So it will take some time to go through all of them ...
